# Generated by Django 3.2.19 on 2023-06-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_detials',
            old_name='user',
            new_name='worker',
        ),
    ]
