# Generated by Django 3.2.19 on 2023-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_rename_user_worker_detials_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_detials',
            name='photo',
            field=models.ImageField(upload_to='workerimages/', verbose_name='image'),
        ),
    ]
