# Generated by Django 3.2.19 on 2023-06-15 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0005_alter_users_is_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Worker', '0003_alter_worker_detials_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker_detials',
            new_name='Worker_details',
        ),
    ]
