# Generated by Django 3.2.19 on 2023-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0004_rename_worker_detials_worker_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_details',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
