# Generated by Django 3.2.19 on 2023-06-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_user',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
