# Generated by Django 3.2.19 on 2023-06-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0002_alter_users_is_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
