# Generated by Django 3.2.19 on 2023-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0002_alter_users_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
