# Generated by Django 3.2.19 on 2023-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0003_booking_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='is_user',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=0),
        ),
    ]
