# Generated by Django 3.2.19 on 2023-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0003_users_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
