# Generated by Django 3.2.19 on 2023-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0004_auto_20230707_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_user',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
