# Generated by Django 3.2.19 on 2023-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0005_alter_users_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_user',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
