# Generated by Django 4.2 on 2023-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0007_alter_users_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
